// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16/05/2026, 20:35:20
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/HP/pessoal/ogum7lancas/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/pessoal/ogum7lancas/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/pessoal/ogum7lancas/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/pessoal/ogum7lancas/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/pessoal/ogum7lancas/plugins/**/*.{js,ts,mjs}","C:/Users/HP/pessoal/ogum7lancas/composables/**/*.{js,ts,mjs}","C:/Users/HP/pessoal/ogum7lancas/utils/**/*.{js,ts,mjs}","C:/Users/HP/pessoal/ogum7lancas/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/pessoal/ogum7lancas/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/pessoal/ogum7lancas/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HP/pessoal/ogum7lancas/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;